// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: browser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserRegistration_StartRegister_FullMethodName    = "/browser.BrowserRegistration/StartRegister"
	BrowserRegistration_CompleteRegister_FullMethodName = "/browser.BrowserRegistration/CompleteRegister"
	BrowserRegistration_CancelRegister_FullMethodName   = "/browser.BrowserRegistration/CancelRegister"
)

// BrowserRegistrationClient is the client API for BrowserRegistration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrowserRegistrationClient interface {
	StartRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StartRegisterResponse, error)
	CompleteRegister(ctx context.Context, in *CompleteRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	CancelRegister(ctx context.Context, in *CancelRegisterRequest, opts ...grpc.CallOption) (*CancelRegisterResponse, error)
}

type browserRegistrationClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserRegistrationClient(cc grpc.ClientConnInterface) BrowserRegistrationClient {
	return &browserRegistrationClient{cc}
}

func (c *browserRegistrationClient) StartRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StartRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRegisterResponse)
	err := c.cc.Invoke(ctx, BrowserRegistration_StartRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserRegistrationClient) CompleteRegister(ctx context.Context, in *CompleteRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, BrowserRegistration_CompleteRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserRegistrationClient) CancelRegister(ctx context.Context, in *CancelRegisterRequest, opts ...grpc.CallOption) (*CancelRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRegisterResponse)
	err := c.cc.Invoke(ctx, BrowserRegistration_CancelRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserRegistrationServer is the server API for BrowserRegistration service.
// All implementations must embed UnimplementedBrowserRegistrationServer
// for forward compatibility.
type BrowserRegistrationServer interface {
	StartRegister(context.Context, *RegisterRequest) (*StartRegisterResponse, error)
	CompleteRegister(context.Context, *CompleteRegisterRequest) (*RegisterResponse, error)
	CancelRegister(context.Context, *CancelRegisterRequest) (*CancelRegisterResponse, error)
	mustEmbedUnimplementedBrowserRegistrationServer()
}

// UnimplementedBrowserRegistrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserRegistrationServer struct{}

func (UnimplementedBrowserRegistrationServer) StartRegister(context.Context, *RegisterRequest) (*StartRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRegister not implemented")
}
func (UnimplementedBrowserRegistrationServer) CompleteRegister(context.Context, *CompleteRegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteRegister not implemented")
}
func (UnimplementedBrowserRegistrationServer) CancelRegister(context.Context, *CancelRegisterRequest) (*CancelRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRegister not implemented")
}
func (UnimplementedBrowserRegistrationServer) mustEmbedUnimplementedBrowserRegistrationServer() {}
func (UnimplementedBrowserRegistrationServer) testEmbeddedByValue()                             {}

// UnsafeBrowserRegistrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserRegistrationServer will
// result in compilation errors.
type UnsafeBrowserRegistrationServer interface {
	mustEmbedUnimplementedBrowserRegistrationServer()
}

func RegisterBrowserRegistrationServer(s grpc.ServiceRegistrar, srv BrowserRegistrationServer) {
	// If the following call pancis, it indicates UnimplementedBrowserRegistrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserRegistration_ServiceDesc, srv)
}

func _BrowserRegistration_StartRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserRegistrationServer).StartRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserRegistration_StartRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserRegistrationServer).StartRegister(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserRegistration_CompleteRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserRegistrationServer).CompleteRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserRegistration_CompleteRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserRegistrationServer).CompleteRegister(ctx, req.(*CompleteRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserRegistration_CancelRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserRegistrationServer).CancelRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserRegistration_CancelRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserRegistrationServer).CancelRegister(ctx, req.(*CancelRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowserRegistration_ServiceDesc is the grpc.ServiceDesc for BrowserRegistration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserRegistration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.BrowserRegistration",
	HandlerType: (*BrowserRegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRegister",
			Handler:    _BrowserRegistration_StartRegister_Handler,
		},
		{
			MethodName: "CompleteRegister",
			Handler:    _BrowserRegistration_CompleteRegister_Handler,
		},
		{
			MethodName: "CancelRegister",
			Handler:    _BrowserRegistration_CancelRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "browser.proto",
}
