// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: browser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AssignedEmail string                 `protobuf:"bytes,2,opt,name=assigned_email,json=assignedEmail,proto3" json:"assigned_email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Birthday      string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RegisterRequest) GetAssignedEmail() string {
	if x != nil {
		return x.AssignedEmail
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionToken      string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	AccessToken       string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId          string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PlusTrialEligible bool                   `protobuf:"varint,6,opt,name=plus_trial_eligible,json=plusTrialEligible,proto3" json:"plus_trial_eligible,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,7,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterResponse) GetPlusTrialEligible() bool {
	if x != nil {
		return x.PlusTrialEligible
	}
	return false
}

func (x *RegisterResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type StartRegisterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FlowId             string                 `protobuf:"bytes,3,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	OtpRequired        bool                   `protobuf:"varint,4,opt,name=otp_required,json=otpRequired,proto3" json:"otp_required,omitempty"`
	Result             *RegisterResponse      `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	OtpIssuedAfterUnix int64                  `protobuf:"varint,6,opt,name=otp_issued_after_unix,json=otpIssuedAfterUnix,proto3" json:"otp_issued_after_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartRegisterResponse) Reset() {
	*x = StartRegisterResponse{}
	mi := &file_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegisterResponse) ProtoMessage() {}

func (x *StartRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegisterResponse.ProtoReflect.Descriptor instead.
func (*StartRegisterResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{2}
}

func (x *StartRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartRegisterResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *StartRegisterResponse) GetOtpRequired() bool {
	if x != nil {
		return x.OtpRequired
	}
	return false
}

func (x *StartRegisterResponse) GetResult() *RegisterResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StartRegisterResponse) GetOtpIssuedAfterUnix() int64 {
	if x != nil {
		return x.OtpIssuedAfterUnix
	}
	return 0
}

type CompleteRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRegisterRequest) Reset() {
	*x = CompleteRegisterRequest{}
	mi := &file_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRegisterRequest) ProtoMessage() {}

func (x *CompleteRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRegisterRequest.ProtoReflect.Descriptor instead.
func (*CompleteRegisterRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRegisterRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *CompleteRegisterRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type CancelRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegisterRequest) Reset() {
	*x = CancelRegisterRequest{}
	mi := &file_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegisterRequest) ProtoMessage() {}

func (x *CancelRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegisterRequest.ProtoReflect.Descriptor instead.
func (*CancelRegisterRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRegisterRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type CancelRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegisterResponse) Reset() {
	*x = CancelRegisterResponse{}
	mi := &file_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegisterResponse) ProtoMessage() {}

func (x *CancelRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegisterResponse.ProtoReflect.Descriptor instead.
func (*CancelRegisterResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelRegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_browser_proto protoreflect.FileDescriptor

const file_browser_proto_rawDesc = "" +
	"\n" +
	"\rbrowser.proto\x12\abrowser\"\xc9\x01\n" +
	"\x0fRegisterRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0eassigned_email\x18\x02 \x01(\tR\rassignedEmail\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthdayJ\x04\b\x03\x10\x04\"\x89\x02\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12.\n" +
	"\x13plus_trial_eligible\x18\x06 \x01(\bR\x11plusTrialEligible\x12!\n" +
	"\fcheckout_url\x18\a \x01(\tR\vcheckoutUrl\"\xf8\x01\n" +
	"\x15StartRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\aflow_id\x18\x03 \x01(\tR\x06flowId\x12!\n" +
	"\fotp_required\x18\x04 \x01(\bR\votpRequired\x121\n" +
	"\x06result\x18\x05 \x01(\v2\x19.browser.RegisterResponseR\x06result\x121\n" +
	"\x15otp_issued_after_unix\x18\x06 \x01(\x03R\x12otpIssuedAfterUnix\"D\n" +
	"\x17CompleteRegisterRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"0\n" +
	"\x15CancelRegisterRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"W\n" +
	"\x16CancelRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x84\x02\n" +
	"\x13BrowserRegistration\x12I\n" +
	"\rStartRegister\x12\x18.browser.RegisterRequest\x1a\x1e.browser.StartRegisterResponse\x12O\n" +
	"\x10CompleteRegister\x12 .browser.CompleteRegisterRequest\x1a\x19.browser.RegisterResponse\x12Q\n" +
	"\x0eCancelRegister\x12\x1e.browser.CancelRegisterRequest\x1a\x1f.browser.CancelRegisterResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_browser_proto_rawDescOnce sync.Once
	file_browser_proto_rawDescData []byte
)

func file_browser_proto_rawDescGZIP() []byte {
	file_browser_proto_rawDescOnce.Do(func() {
		file_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browser_proto_rawDesc), len(file_browser_proto_rawDesc)))
	})
	return file_browser_proto_rawDescData
}

var file_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_browser_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: browser.RegisterRequest
	(*RegisterResponse)(nil),        // 1: browser.RegisterResponse
	(*StartRegisterResponse)(nil),   // 2: browser.StartRegisterResponse
	(*CompleteRegisterRequest)(nil), // 3: browser.CompleteRegisterRequest
	(*CancelRegisterRequest)(nil),   // 4: browser.CancelRegisterRequest
	(*CancelRegisterResponse)(nil),  // 5: browser.CancelRegisterResponse
}
var file_browser_proto_depIdxs = []int32{
	1, // 0: browser.StartRegisterResponse.result:type_name -> browser.RegisterResponse
	0, // 1: browser.BrowserRegistration.StartRegister:input_type -> browser.RegisterRequest
	3, // 2: browser.BrowserRegistration.CompleteRegister:input_type -> browser.CompleteRegisterRequest
	4, // 3: browser.BrowserRegistration.CancelRegister:input_type -> browser.CancelRegisterRequest
	2, // 4: browser.BrowserRegistration.StartRegister:output_type -> browser.StartRegisterResponse
	1, // 5: browser.BrowserRegistration.CompleteRegister:output_type -> browser.RegisterResponse
	5, // 6: browser.BrowserRegistration.CancelRegister:output_type -> browser.CancelRegisterResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_browser_proto_init() }
func file_browser_proto_init() {
	if File_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browser_proto_rawDesc), len(file_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browser_proto_goTypes,
		DependencyIndexes: file_browser_proto_depIdxs,
		MessageInfos:      file_browser_proto_msgTypes,
	}.Build()
	File_browser_proto = out.File
	file_browser_proto_goTypes = nil
	file_browser_proto_depIdxs = nil
}
