// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: email.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitForEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmailAddress    string                 `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	SubjectKeyword  string                 `protobuf:"bytes,2,opt,name=subject_keyword,json=subjectKeyword,proto3" json:"subject_keyword,omitempty"` // e.g., "OTP" or "验证码"
	TimeoutSeconds  int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IssuedAfterUnix int64                  `protobuf:"varint,4,opt,name=issued_after_unix,json=issuedAfterUnix,proto3" json:"issued_after_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WaitForEmailRequest) Reset() {
	*x = WaitForEmailRequest{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForEmailRequest) ProtoMessage() {}

func (x *WaitForEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForEmailRequest.ProtoReflect.Descriptor instead.
func (*WaitForEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *WaitForEmailRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *WaitForEmailRequest) GetSubjectKeyword() string {
	if x != nil {
		return x.SubjectKeyword
	}
	return ""
}

func (x *WaitForEmailRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *WaitForEmailRequest) GetIssuedAfterUnix() int64 {
	if x != nil {
		return x.IssuedAfterUnix
	}
	return 0
}

type WaitForEmailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Found            bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ContentExtracted string                 `protobuf:"bytes,2,opt,name=content_extracted,json=contentExtracted,proto3" json:"content_extracted,omitempty"` // the OTP
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WaitForEmailResponse) Reset() {
	*x = WaitForEmailResponse{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForEmailResponse) ProtoMessage() {}

func (x *WaitForEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForEmailResponse.ProtoReflect.Descriptor instead.
func (*WaitForEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *WaitForEmailResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *WaitForEmailResponse) GetContentExtracted() string {
	if x != nil {
		return x.ContentExtracted
	}
	return ""
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\x05email\"\xb8\x01\n" +
	"\x13WaitForEmailRequest\x12#\n" +
	"\remail_address\x18\x01 \x01(\tR\femailAddress\x12'\n" +
	"\x0fsubject_keyword\x18\x02 \x01(\tR\x0esubjectKeyword\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12*\n" +
	"\x11issued_after_unix\x18\x04 \x01(\x03R\x0fissuedAfterUnix\"Y\n" +
	"\x14WaitForEmailResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x11content_extracted\x18\x02 \x01(\tR\x10contentExtracted2W\n" +
	"\fEmailService\x12G\n" +
	"\fWaitForEmail\x12\x1a.email.WaitForEmailRequest\x1a\x1b.email.WaitForEmailResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_proto_goTypes = []any{
	(*WaitForEmailRequest)(nil),  // 0: email.WaitForEmailRequest
	(*WaitForEmailResponse)(nil), // 1: email.WaitForEmailResponse
}
var file_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.WaitForEmail:input_type -> email.WaitForEmailRequest
	1, // 1: email.EmailService.WaitForEmail:output_type -> email.WaitForEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
