// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orchestrator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountRequest) Reset() {
	*x = RequestAccountRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountRequest) ProtoMessage() {}

func (x *RequestAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type RequestAccountResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionToken      string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	PlusTrialEligible bool                   `protobuf:"varint,3,opt,name=plus_trial_eligible,json=plusTrialEligible,proto3" json:"plus_trial_eligible,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,5,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	AccessToken       string                 `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestAccountResponse) Reset() {
	*x = RequestAccountResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountResponse) ProtoMessage() {}

func (x *RequestAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountResponse.ProtoReflect.Descriptor instead.
func (*RequestAccountResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *RequestAccountResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestAccountResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RequestAccountResponse) GetPlusTrialEligible() bool {
	if x != nil {
		return x.PlusTrialEligible
	}
	return false
}

func (x *RequestAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RequestAccountResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *RequestAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RegisterAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AccountId     string                 `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RegisterAccountResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionToken      string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	PlusTrialEligible bool                   `protobuf:"varint,3,opt,name=plus_trial_eligible,json=plusTrialEligible,proto3" json:"plus_trial_eligible,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,5,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	AccessToken       string                 `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAccountResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RegisterAccountResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterAccountResponse) GetPlusTrialEligible() bool {
	if x != nil {
		return x.PlusTrialEligible
	}
	return false
}

func (x *RegisterAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterAccountResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *RegisterAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ActivateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existing registration job_id used to resolve account_id.
	// The response returns a new activation job_id.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AccountId     string `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccountRequest) Reset() {
	*x = ActivateAccountRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccountRequest) ProtoMessage() {}

func (x *ActivateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccountRequest.ProtoReflect.Descriptor instead.
func (*ActivateAccountRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateAccountRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActivateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ActivateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChargeRef     string                 `protobuf:"bytes,4,opt,name=charge_ref,json=chargeRef,proto3" json:"charge_ref,omitempty"`
	SnapToken     string                 `protobuf:"bytes,5,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccountResponse) Reset() {
	*x = ActivateAccountResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccountResponse) ProtoMessage() {}

func (x *ActivateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccountResponse.ProtoReflect.Descriptor instead.
func (*ActivateAccountResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ActivateAccountResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActivateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivateAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ActivateAccountResponse) GetChargeRef() string {
	if x != nil {
		return x.ChargeRef
	}
	return ""
}

func (x *ActivateAccountResponse) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

type RegisterAndActivateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	AccountId     string                 `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAndActivateAccountRequest) Reset() {
	*x = RegisterAndActivateAccountRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAndActivateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAndActivateAccountRequest) ProtoMessage() {}

func (x *RegisterAndActivateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAndActivateAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAndActivateAccountRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAndActivateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAndActivateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAndActivateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RegisterAndActivateAccountResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SessionToken      string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	PlusTrialEligible bool                   `protobuf:"varint,3,opt,name=plus_trial_eligible,json=plusTrialEligible,proto3" json:"plus_trial_eligible,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,4,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	ActivationSuccess bool                   `protobuf:"varint,5,opt,name=activation_success,json=activationSuccess,proto3" json:"activation_success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChargeRef         string                 `protobuf:"bytes,7,opt,name=charge_ref,json=chargeRef,proto3" json:"charge_ref,omitempty"`
	SnapToken         string                 `protobuf:"bytes,8,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	AccessToken       string                 `protobuf:"bytes,9,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAndActivateAccountResponse) Reset() {
	*x = RegisterAndActivateAccountResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAndActivateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAndActivateAccountResponse) ProtoMessage() {}

func (x *RegisterAndActivateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAndActivateAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAndActivateAccountResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterAndActivateAccountResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetPlusTrialEligible() bool {
	if x != nil {
		return x.PlusTrialEligible
	}
	return false
}

func (x *RegisterAndActivateAccountResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetActivationSuccess() bool {
	if x != nil {
		return x.ActivationSuccess
	}
	return false
}

func (x *RegisterAndActivateAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetChargeRef() string {
	if x != nil {
		return x.ChargeRef
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

func (x *RegisterAndActivateAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type JobStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Recoverable   bool                   `protobuf:"varint,3,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResultJson    string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStep) Reset() {
	*x = JobStep{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStep) ProtoMessage() {}

func (x *JobStep) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStep.ProtoReflect.Descriptor instead.
func (*JobStep) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *JobStep) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *JobStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStep) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

func (x *JobStep) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *JobStep) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStep) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *JobStep) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobStep) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Recoverable   bool                   `protobuf:"varint,5,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	Retryable     bool                   `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	LastStep      string                 `protobuf:"bytes,7,opt,name=last_step,json=lastStep,proto3" json:"last_step,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResultJson    string                 `protobuf:"bytes,9,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Steps         []*JobStep             `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Job) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

func (x *Job) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Job) GetLastStep() string {
	if x != nil {
		return x.LastStep
	}
	return ""
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Job) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Job) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Job) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Job) GetSteps() []*JobStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\forchestrator\"\x17\n" +
	"\x15RequestAccountRequest\"\xef\x01\n" +
	"\x16RequestAccountResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12.\n" +
	"\x13plus_trial_eligible\x18\x03 \x01(\bR\x11plusTrialEligible\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcheckout_url\x18\x05 \x01(\tR\vcheckoutUrl\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessToken\"\x97\x01\n" +
	"\x16RegisterAccountRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tR\taccountIdJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\n" +
	"first_nameR\tlast_nameR\x03dob\"\xf0\x01\n" +
	"\x17RegisterAccountResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12.\n" +
	"\x13plus_trial_eligible\x18\x03 \x01(\bR\x11plusTrialEligible\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcheckout_url\x18\x05 \x01(\tR\vcheckoutUrl\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessToken\"x\n" +
	"\x16ActivateAccountRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\tR\taccountIdJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\t\"\xad\x01\n" +
	"\x17ActivateAccountResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"charge_ref\x18\x04 \x01(\tR\tchargeRef\x12\x1d\n" +
	"\n" +
	"snap_token\x18\x05 \x01(\tR\tsnapToken\"\xa4\x01\n" +
	"!RegisterAndActivateAccountRequest\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountIdJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\v\"\xe8\x02\n" +
	"\"RegisterAndActivateAccountResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12.\n" +
	"\x13plus_trial_eligible\x18\x03 \x01(\bR\x11plusTrialEligible\x12!\n" +
	"\fcheckout_url\x18\x04 \x01(\tR\vcheckoutUrl\x12-\n" +
	"\x12activation_success\x18\x05 \x01(\bR\x11activationSuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"charge_ref\x18\a \x01(\tR\tchargeRef\x12\x1d\n" +
	"\n" +
	"snap_token\x18\b \x01(\tR\tsnapToken\x12!\n" +
	"\faccess_token\x18\t \x01(\tR\vaccessToken\"\x86\x02\n" +
	"\aJobStep\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vrecoverable\x18\x03 \x01(\bR\vrecoverable\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\"\xf9\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vrecoverable\x18\x05 \x01(\bR\vrecoverable\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x12\x1b\n" +
	"\tlast_step\x18\a \x01(\tR\blastStep\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vresult_json\x18\t \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12+\n" +
	"\x05steps\x18\f \x03(\v2\x15.orchestrator.JobStepR\x05steps\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"Z\n" +
	"\x0eGetJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.orchestrator.JobR\x03job\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xf8\x03\n" +
	"\x13OrchestratorService\x12^\n" +
	"\x0fRegisterAccount\x12$.orchestrator.RegisterAccountRequest\x1a%.orchestrator.RegisterAccountResponse\x12^\n" +
	"\x0fActivateAccount\x12$.orchestrator.ActivateAccountRequest\x1a%.orchestrator.ActivateAccountResponse\x12\x7f\n" +
	"\x1aRegisterAndActivateAccount\x12/.orchestrator.RegisterAndActivateAccountRequest\x1a0.orchestrator.RegisterAndActivateAccountResponse\x12C\n" +
	"\x06GetJob\x12\x1b.orchestrator.GetJobRequest\x1a\x1c.orchestrator.GetJobResponse\x12[\n" +
	"\x0eRequestAccount\x12#.orchestrator.RequestAccountRequest\x1a$.orchestrator.RequestAccountResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_orchestrator_proto_goTypes = []any{
	(*RequestAccountRequest)(nil),              // 0: orchestrator.RequestAccountRequest
	(*RequestAccountResponse)(nil),             // 1: orchestrator.RequestAccountResponse
	(*RegisterAccountRequest)(nil),             // 2: orchestrator.RegisterAccountRequest
	(*RegisterAccountResponse)(nil),            // 3: orchestrator.RegisterAccountResponse
	(*ActivateAccountRequest)(nil),             // 4: orchestrator.ActivateAccountRequest
	(*ActivateAccountResponse)(nil),            // 5: orchestrator.ActivateAccountResponse
	(*RegisterAndActivateAccountRequest)(nil),  // 6: orchestrator.RegisterAndActivateAccountRequest
	(*RegisterAndActivateAccountResponse)(nil), // 7: orchestrator.RegisterAndActivateAccountResponse
	(*JobStep)(nil),                            // 8: orchestrator.JobStep
	(*Job)(nil),                                // 9: orchestrator.Job
	(*GetJobRequest)(nil),                      // 10: orchestrator.GetJobRequest
	(*GetJobResponse)(nil),                     // 11: orchestrator.GetJobResponse
}
var file_orchestrator_proto_depIdxs = []int32{
	8,  // 0: orchestrator.Job.steps:type_name -> orchestrator.JobStep
	9,  // 1: orchestrator.GetJobResponse.job:type_name -> orchestrator.Job
	2,  // 2: orchestrator.OrchestratorService.RegisterAccount:input_type -> orchestrator.RegisterAccountRequest
	4,  // 3: orchestrator.OrchestratorService.ActivateAccount:input_type -> orchestrator.ActivateAccountRequest
	6,  // 4: orchestrator.OrchestratorService.RegisterAndActivateAccount:input_type -> orchestrator.RegisterAndActivateAccountRequest
	10, // 5: orchestrator.OrchestratorService.GetJob:input_type -> orchestrator.GetJobRequest
	0,  // 6: orchestrator.OrchestratorService.RequestAccount:input_type -> orchestrator.RequestAccountRequest
	3,  // 7: orchestrator.OrchestratorService.RegisterAccount:output_type -> orchestrator.RegisterAccountResponse
	5,  // 8: orchestrator.OrchestratorService.ActivateAccount:output_type -> orchestrator.ActivateAccountResponse
	7,  // 9: orchestrator.OrchestratorService.RegisterAndActivateAccount:output_type -> orchestrator.RegisterAndActivateAccountResponse
	11, // 10: orchestrator.OrchestratorService.GetJob:output_type -> orchestrator.GetJobResponse
	1,  // 11: orchestrator.OrchestratorService.RequestAccount:output_type -> orchestrator.RequestAccountResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
