// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: otp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitForOtpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Purpose         string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IssuedAfterUnix int64                  `protobuf:"varint,3,opt,name=issued_after_unix,json=issuedAfterUnix,proto3" json:"issued_after_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WaitForOtpRequest) Reset() {
	*x = WaitForOtpRequest{}
	mi := &file_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForOtpRequest) ProtoMessage() {}

func (x *WaitForOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForOtpRequest.ProtoReflect.Descriptor instead.
func (*WaitForOtpRequest) Descriptor() ([]byte, []int) {
	return file_otp_proto_rawDescGZIP(), []int{0}
}

func (x *WaitForOtpRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *WaitForOtpRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *WaitForOtpRequest) GetIssuedAfterUnix() int64 {
	if x != nil {
		return x.IssuedAfterUnix
	}
	return 0
}

type WaitForOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForOtpResponse) Reset() {
	*x = WaitForOtpResponse{}
	mi := &file_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForOtpResponse) ProtoMessage() {}

func (x *WaitForOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForOtpResponse.ProtoReflect.Descriptor instead.
func (*WaitForOtpResponse) Descriptor() ([]byte, []int) {
	return file_otp_proto_rawDescGZIP(), []int{1}
}

func (x *WaitForOtpResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *WaitForOtpResponse) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *WaitForOtpResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WaitForOtpResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_otp_proto protoreflect.FileDescriptor

const file_otp_proto_rawDesc = "" +
	"\n" +
	"\totp.proto\x12\x03otp\"\x82\x01\n" +
	"\x11WaitForOtpRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12*\n" +
	"\x11issued_after_unix\x18\x03 \x01(\x03R\x0fissuedAfterUnix\"y\n" +
	"\x12WaitForOtpResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2K\n" +
	"\n" +
	"OtpService\x12=\n" +
	"\n" +
	"WaitForOtp\x12\x16.otp.WaitForOtpRequest\x1a\x17.otp.WaitForOtpResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_otp_proto_rawDescOnce sync.Once
	file_otp_proto_rawDescData []byte
)

func file_otp_proto_rawDescGZIP() []byte {
	file_otp_proto_rawDescOnce.Do(func() {
		file_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otp_proto_rawDesc), len(file_otp_proto_rawDesc)))
	})
	return file_otp_proto_rawDescData
}

var file_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_otp_proto_goTypes = []any{
	(*WaitForOtpRequest)(nil),  // 0: otp.WaitForOtpRequest
	(*WaitForOtpResponse)(nil), // 1: otp.WaitForOtpResponse
}
var file_otp_proto_depIdxs = []int32{
	0, // 0: otp.OtpService.WaitForOtp:input_type -> otp.WaitForOtpRequest
	1, // 1: otp.OtpService.WaitForOtp:output_type -> otp.WaitForOtpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_otp_proto_init() }
func file_otp_proto_init() {
	if File_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otp_proto_rawDesc), len(file_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otp_proto_goTypes,
		DependencyIndexes: file_otp_proto_depIdxs,
		MessageInfos:      file_otp_proto_msgTypes,
	}.Build()
	File_otp_proto = out.File
	file_otp_proto_goTypes = nil
	file_otp_proto_depIdxs = nil
}
