// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: payment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_StartGoPay_FullMethodName    = "/payment.PaymentService/StartGoPay"
	PaymentService_CompleteGoPay_FullMethodName = "/payment.PaymentService/CompleteGoPay"
	PaymentService_CancelGoPay_FullMethodName   = "/payment.PaymentService/CancelGoPay"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	StartGoPay(ctx context.Context, in *StartGoPayRequest, opts ...grpc.CallOption) (*StartGoPayResponse, error)
	CompleteGoPay(ctx context.Context, in *CompleteGoPayRequest, opts ...grpc.CallOption) (*GoPayResponse, error)
	CancelGoPay(ctx context.Context, in *CancelGoPayRequest, opts ...grpc.CallOption) (*CancelGoPayResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) StartGoPay(ctx context.Context, in *StartGoPayRequest, opts ...grpc.CallOption) (*StartGoPayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGoPayResponse)
	err := c.cc.Invoke(ctx, PaymentService_StartGoPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CompleteGoPay(ctx context.Context, in *CompleteGoPayRequest, opts ...grpc.CallOption) (*GoPayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoPayResponse)
	err := c.cc.Invoke(ctx, PaymentService_CompleteGoPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelGoPay(ctx context.Context, in *CancelGoPayRequest, opts ...grpc.CallOption) (*CancelGoPayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelGoPayResponse)
	err := c.cc.Invoke(ctx, PaymentService_CancelGoPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	StartGoPay(context.Context, *StartGoPayRequest) (*StartGoPayResponse, error)
	CompleteGoPay(context.Context, *CompleteGoPayRequest) (*GoPayResponse, error)
	CancelGoPay(context.Context, *CancelGoPayRequest) (*CancelGoPayResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) StartGoPay(context.Context, *StartGoPayRequest) (*StartGoPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGoPay not implemented")
}
func (UnimplementedPaymentServiceServer) CompleteGoPay(context.Context, *CompleteGoPayRequest) (*GoPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteGoPay not implemented")
}
func (UnimplementedPaymentServiceServer) CancelGoPay(context.Context, *CancelGoPayRequest) (*CancelGoPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelGoPay not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_StartGoPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGoPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StartGoPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_StartGoPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StartGoPay(ctx, req.(*StartGoPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CompleteGoPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteGoPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CompleteGoPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CompleteGoPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CompleteGoPay(ctx, req.(*CompleteGoPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelGoPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGoPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelGoPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CancelGoPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelGoPay(ctx, req.(*CancelGoPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGoPay",
			Handler:    _PaymentService_StartGoPay_Handler,
		},
		{
			MethodName: "CompleteGoPay",
			Handler:    _PaymentService_CompleteGoPay_Handler,
		},
		{
			MethodName: "CancelGoPay",
			Handler:    _PaymentService_CancelGoPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
