// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGoPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGoPayRequest) Reset() {
	*x = StartGoPayRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGoPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGoPayRequest) ProtoMessage() {}

func (x *StartGoPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGoPayRequest.ProtoReflect.Descriptor instead.
func (*StartGoPayRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *StartGoPayRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StartGoPayRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type StartGoPayResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FlowId          string                 `protobuf:"bytes,3,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	SnapToken       string                 `protobuf:"bytes,4,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	IssuedAfterUnix int64                  `protobuf:"varint,5,opt,name=issued_after_unix,json=issuedAfterUnix,proto3" json:"issued_after_unix,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartGoPayResponse) Reset() {
	*x = StartGoPayResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGoPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGoPayResponse) ProtoMessage() {}

func (x *StartGoPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGoPayResponse.ProtoReflect.Descriptor instead.
func (*StartGoPayResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *StartGoPayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartGoPayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartGoPayResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *StartGoPayResponse) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

func (x *StartGoPayResponse) GetIssuedAfterUnix() int64 {
	if x != nil {
		return x.IssuedAfterUnix
	}
	return 0
}

func (x *StartGoPayResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CompleteGoPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteGoPayRequest) Reset() {
	*x = CompleteGoPayRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteGoPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteGoPayRequest) ProtoMessage() {}

func (x *CompleteGoPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteGoPayRequest.ProtoReflect.Descriptor instead.
func (*CompleteGoPayRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteGoPayRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *CompleteGoPayRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type CancelGoPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoPayRequest) Reset() {
	*x = CancelGoPayRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoPayRequest) ProtoMessage() {}

func (x *CancelGoPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoPayRequest.ProtoReflect.Descriptor instead.
func (*CancelGoPayRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CancelGoPayRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type CancelGoPayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoPayResponse) Reset() {
	*x = CancelGoPayResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoPayResponse) ProtoMessage() {}

func (x *CancelGoPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoPayResponse.ProtoReflect.Descriptor instead.
func (*CancelGoPayResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CancelGoPayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelGoPayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GoPayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChargeRef     string                 `protobuf:"bytes,3,opt,name=charge_ref,json=chargeRef,proto3" json:"charge_ref,omitempty"`
	SnapToken     string                 `protobuf:"bytes,4,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoPayResponse) Reset() {
	*x = GoPayResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoPayResponse) ProtoMessage() {}

func (x *GoPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoPayResponse.ProtoReflect.Descriptor instead.
func (*GoPayResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GoPayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GoPayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GoPayResponse) GetChargeRef() string {
	if x != nil {
		return x.ChargeRef
	}
	return ""
}

func (x *GoPayResponse) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"s\n" +
	"\x11StartGoPayRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessTokenJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"\xdf\x01\n" +
	"\x12StartGoPayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\aflow_id\x18\x03 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"snap_token\x18\x04 \x01(\tR\tsnapToken\x12*\n" +
	"\x11issued_after_unix\x18\x05 \x01(\x03R\x0fissuedAfterUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix\"A\n" +
	"\x14CompleteGoPayRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"-\n" +
	"\x12CancelGoPayRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"T\n" +
	"\x13CancelGoPayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8c\x01\n" +
	"\rGoPayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"charge_ref\x18\x03 \x01(\tR\tchargeRef\x12\x1d\n" +
	"\n" +
	"snap_token\x18\x04 \x01(\tR\tsnapToken2\xe9\x01\n" +
	"\x0ePaymentService\x12E\n" +
	"\n" +
	"StartGoPay\x12\x1a.payment.StartGoPayRequest\x1a\x1b.payment.StartGoPayResponse\x12F\n" +
	"\rCompleteGoPay\x12\x1d.payment.CompleteGoPayRequest\x1a\x16.payment.GoPayResponse\x12H\n" +
	"\vCancelGoPay\x12\x1b.payment.CancelGoPayRequest\x1a\x1c.payment.CancelGoPayResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(*StartGoPayRequest)(nil),    // 0: payment.StartGoPayRequest
	(*StartGoPayResponse)(nil),   // 1: payment.StartGoPayResponse
	(*CompleteGoPayRequest)(nil), // 2: payment.CompleteGoPayRequest
	(*CancelGoPayRequest)(nil),   // 3: payment.CancelGoPayRequest
	(*CancelGoPayResponse)(nil),  // 4: payment.CancelGoPayResponse
	(*GoPayResponse)(nil),        // 5: payment.GoPayResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.StartGoPay:input_type -> payment.StartGoPayRequest
	2, // 1: payment.PaymentService.CompleteGoPay:input_type -> payment.CompleteGoPayRequest
	3, // 2: payment.PaymentService.CancelGoPay:input_type -> payment.CancelGoPayRequest
	1, // 3: payment.PaymentService.StartGoPay:output_type -> payment.StartGoPayResponse
	5, // 4: payment.PaymentService.CompleteGoPay:output_type -> payment.GoPayResponse
	4, // 5: payment.PaymentService.CancelGoPay:output_type -> payment.CancelGoPayResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
