# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: browser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'browser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbrowser.proto\x12\x07\x62rowser\"\x8a\x01\n\x0fRegisterRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61ssigned_email\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\x10\n\x08\x62irthday\x18\x07 \x01(\tJ\x04\x08\x03\x10\x04\"\xad\x01\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x04 \x01(\t\x12\x11\n\tdevice_id\x18\x05 \x01(\t\x12\x1b\n\x13plus_trial_eligible\x18\x06 \x01(\x08\x12\x14\n\x0c\x63heckout_url\x18\x07 \x01(\t\"\xb0\x01\n\x15StartRegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0f\n\x07\x66low_id\x18\x03 \x01(\t\x12\x14\n\x0cotp_required\x18\x04 \x01(\x08\x12)\n\x06result\x18\x05 \x01(\x0b\x32\x19.browser.RegisterResponse\x12\x1d\n\x15otp_issued_after_unix\x18\x06 \x01(\x03\"7\n\x17\x43ompleteRegisterRequest\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"(\n\x15\x43\x61ncelRegisterRequest\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\"@\n\x16\x43\x61ncelRegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x84\x02\n\x13\x42rowserRegistration\x12I\n\rStartRegister\x12\x18.browser.RegisterRequest\x1a\x1e.browser.StartRegisterResponse\x12O\n\x10\x43ompleteRegister\x12 .browser.CompleteRegisterRequest\x1a\x19.browser.RegisterResponse\x12Q\n\x0e\x43\x61ncelRegister\x12\x1e.browser.CancelRegisterRequest\x1a\x1f.browser.CancelRegisterResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'browser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_REGISTERREQUEST']._serialized_start=27
  _globals['_REGISTERREQUEST']._serialized_end=165
  _globals['_REGISTERRESPONSE']._serialized_start=168
  _globals['_REGISTERRESPONSE']._serialized_end=341
  _globals['_STARTREGISTERRESPONSE']._serialized_start=344
  _globals['_STARTREGISTERRESPONSE']._serialized_end=520
  _globals['_COMPLETEREGISTERREQUEST']._serialized_start=522
  _globals['_COMPLETEREGISTERREQUEST']._serialized_end=577
  _globals['_CANCELREGISTERREQUEST']._serialized_start=579
  _globals['_CANCELREGISTERREQUEST']._serialized_end=619
  _globals['_CANCELREGISTERRESPONSE']._serialized_start=621
  _globals['_CANCELREGISTERRESPONSE']._serialized_end=685
  _globals['_BROWSERREGISTRATION']._serialized_start=688
  _globals['_BROWSERREGISTRATION']._serialized_end=948
# @@protoc_insertion_point(module_scope)
