# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import browser_pb2 as browser__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in browser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrowserRegistrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRegister = channel.unary_unary(
                '/browser.BrowserRegistration/StartRegister',
                request_serializer=browser__pb2.RegisterRequest.SerializeToString,
                response_deserializer=browser__pb2.StartRegisterResponse.FromString,
                _registered_method=True)
        self.CompleteRegister = channel.unary_unary(
                '/browser.BrowserRegistration/CompleteRegister',
                request_serializer=browser__pb2.CompleteRegisterRequest.SerializeToString,
                response_deserializer=browser__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.CancelRegister = channel.unary_unary(
                '/browser.BrowserRegistration/CancelRegister',
                request_serializer=browser__pb2.CancelRegisterRequest.SerializeToString,
                response_deserializer=browser__pb2.CancelRegisterResponse.FromString,
                _registered_method=True)


class BrowserRegistrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrowserRegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRegister,
                    request_deserializer=browser__pb2.RegisterRequest.FromString,
                    response_serializer=browser__pb2.StartRegisterResponse.SerializeToString,
            ),
            'CompleteRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRegister,
                    request_deserializer=browser__pb2.CompleteRegisterRequest.FromString,
                    response_serializer=browser__pb2.RegisterResponse.SerializeToString,
            ),
            'CancelRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRegister,
                    request_deserializer=browser__pb2.CancelRegisterRequest.FromString,
                    response_serializer=browser__pb2.CancelRegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'browser.BrowserRegistration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('browser.BrowserRegistration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrowserRegistration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserRegistration/StartRegister',
            browser__pb2.RegisterRequest.SerializeToString,
            browser__pb2.StartRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserRegistration/CompleteRegister',
            browser__pb2.CompleteRegisterRequest.SerializeToString,
            browser__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/browser.BrowserRegistration/CancelRegister',
            browser__pb2.CancelRegisterRequest.SerializeToString,
            browser__pb2.CancelRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
