# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: otp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'otp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\totp.proto\x12\x03otp\"X\n\x11WaitForOtpRequest\x12\x0f\n\x07purpose\x18\x01 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\x05\x12\x19\n\x11issued_after_unix\x18\x03 \x01(\x03\"W\n\x12WaitForOtpResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0b\n\x03otp\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2K\n\nOtpService\x12=\n\nWaitForOtp\x12\x16.otp.WaitForOtpRequest\x1a\x17.otp.WaitForOtpResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_WAITFOROTPREQUEST']._serialized_start=18
  _globals['_WAITFOROTPREQUEST']._serialized_end=106
  _globals['_WAITFOROTPRESPONSE']._serialized_start=108
  _globals['_WAITFOROTPRESPONSE']._serialized_end=195
  _globals['_OTPSERVICE']._serialized_start=197
  _globals['_OTPSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
