# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"X\n\x11StartGoPayRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x06 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06\"\x95\x01\n\x12StartGoPayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0f\n\x07\x66low_id\x18\x03 \x01(\t\x12\x12\n\nsnap_token\x18\x04 \x01(\t\x12\x19\n\x11issued_after_unix\x18\x05 \x01(\x03\x12\x17\n\x0f\x65xpires_at_unix\x18\x06 \x01(\x03\"4\n\x14\x43ompleteGoPayRequest\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"%\n\x12\x43\x61ncelGoPayRequest\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\"=\n\x13\x43\x61ncelGoPayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"_\n\rGoPayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x12\n\ncharge_ref\x18\x03 \x01(\t\x12\x12\n\nsnap_token\x18\x04 \x01(\t2\xe9\x01\n\x0ePaymentService\x12\x45\n\nStartGoPay\x12\x1a.payment.StartGoPayRequest\x1a\x1b.payment.StartGoPayResponse\x12\x46\n\rCompleteGoPay\x12\x1d.payment.CompleteGoPayRequest\x1a\x16.payment.GoPayResponse\x12H\n\x0b\x43\x61ncelGoPay\x12\x1b.payment.CancelGoPayRequest\x1a\x1c.payment.CancelGoPayResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_STARTGOPAYREQUEST']._serialized_start=26
  _globals['_STARTGOPAYREQUEST']._serialized_end=114
  _globals['_STARTGOPAYRESPONSE']._serialized_start=117
  _globals['_STARTGOPAYRESPONSE']._serialized_end=266
  _globals['_COMPLETEGOPAYREQUEST']._serialized_start=268
  _globals['_COMPLETEGOPAYREQUEST']._serialized_end=320
  _globals['_CANCELGOPAYREQUEST']._serialized_start=322
  _globals['_CANCELGOPAYREQUEST']._serialized_end=359
  _globals['_CANCELGOPAYRESPONSE']._serialized_start=361
  _globals['_CANCELGOPAYRESPONSE']._serialized_end=422
  _globals['_GOPAYRESPONSE']._serialized_start=424
  _globals['_GOPAYRESPONSE']._serialized_end=519
  _globals['_PAYMENTSERVICE']._serialized_start=522
  _globals['_PAYMENTSERVICE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
