# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGoPay = channel.unary_unary(
                '/payment.PaymentService/StartGoPay',
                request_serializer=payment__pb2.StartGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.StartGoPayResponse.FromString,
                _registered_method=True)
        self.CompleteGoPay = channel.unary_unary(
                '/payment.PaymentService/CompleteGoPay',
                request_serializer=payment__pb2.CompleteGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.GoPayResponse.FromString,
                _registered_method=True)
        self.CancelGoPay = channel.unary_unary(
                '/payment.PaymentService/CancelGoPay',
                request_serializer=payment__pb2.CancelGoPayRequest.SerializeToString,
                response_deserializer=payment__pb2.CancelGoPayResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGoPay,
                    request_deserializer=payment__pb2.StartGoPayRequest.FromString,
                    response_serializer=payment__pb2.StartGoPayResponse.SerializeToString,
            ),
            'CompleteGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteGoPay,
                    request_deserializer=payment__pb2.CompleteGoPayRequest.FromString,
                    response_serializer=payment__pb2.GoPayResponse.SerializeToString,
            ),
            'CancelGoPay': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoPay,
                    request_deserializer=payment__pb2.CancelGoPayRequest.FromString,
                    response_serializer=payment__pb2.CancelGoPayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/StartGoPay',
            payment__pb2.StartGoPayRequest.SerializeToString,
            payment__pb2.StartGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CompleteGoPay',
            payment__pb2.CompleteGoPayRequest.SerializeToString,
            payment__pb2.GoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CancelGoPay',
            payment__pb2.CancelGoPayRequest.SerializeToString,
            payment__pb2.CancelGoPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
