// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: account_db.proto

/* eslint-disable */

export const protobufPackage = "accountdb";

export interface Account {
  account_id: string;
  email: string;
  password: string;
  status: string;
  error_message: string;
  session_token: string;
  charge_ref: string;
  first_name: string;
  last_name: string;
  /** YYYY-MM-DD */
  dob: string;
  created_at: number;
  updated_at: number;
  access_token: string;
  plus_trial_eligible?: boolean | undefined;
  plus_active?: boolean | undefined;
  tier: string;
  activation_channel?: string | undefined;
}

export interface CreateAccountRequest {
  account: Account | undefined;
}

export interface CreateAccountResponse {
  account: Account | undefined;
}

export interface GetAccountRequest {
  account_id: string;
}

export interface GetAccountResponse {
  account: Account | undefined;
}

export interface UpdateAccountRequest {
  account: Account | undefined;
}

export interface UpdateAccountResponse {
  account: Account | undefined;
}

export interface DeleteAccountRequest {
  account_id: string;
}

export interface DeleteAccountResponse {
  ack: boolean;
}

export interface ListAccountsRequest {
  status: string;
  limit: number;
  email: string;
}

export interface ListAccountsResponse {
  accounts: Account[];
}

export interface GPTEmailAllocation {
  email: string;
  primary_email: string;
  is_primary: boolean;
  status: string;
  splittable: boolean;
  assigned_account_id: string;
  last_error: string;
  created_at: number;
  updated_at: number;
}

export interface UpsertGPTEmailAllocationRequest {
  allocation: GPTEmailAllocation | undefined;
}

export interface UpsertGPTEmailAllocationResponse {
  allocation: GPTEmailAllocation | undefined;
}

export interface ListGPTEmailAllocationsRequest {
  status: string;
  limit: number;
  primary_email: string;
  splittable_only: boolean;
}

export interface ListGPTEmailAllocationsResponse {
  allocations: GPTEmailAllocation[];
}

export interface ClaimGPTEmailAllocationRequest {
  email: string;
  account_id: string;
  expected_status: string;
  status: string;
  require_primary_splittable: boolean;
  expected_primary_status: string;
}

export interface ClaimGPTEmailAllocationResponse {
  claimed: boolean;
  allocation: GPTEmailAllocation | undefined;
}

export interface CreateGPTEmailAliasAllocationRequest {
  primary_email: string;
  account_id: string;
}

export interface CreateGPTEmailAliasAllocationResponse {
  created: boolean;
  allocation: GPTEmailAllocation | undefined;
}

export interface MarkGPTEmailAllocationStatusRequest {
  email: string;
  status: string;
  last_error: string;
}

export interface MarkGPTEmailAllocationStatusResponse {
  allocation: GPTEmailAllocation | undefined;
}
