// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: email.proto

/* eslint-disable */

export const protobufPackage = "email";

export interface EmailMailbox {
  email_address: string;
  password: string;
  refresh_token: string;
  access_token: string;
  status: string;
  last_error: string;
  is_primary: boolean;
  primary_email: string;
  created_at: number;
  updated_at: number;
  latest_otp: string;
  latest_otp_subject: string;
  latest_otp_received_at_unix: number;
  auth_status: string;
}

export interface MarkEmailAuthStatusRequest {
  email_address: string;
  auth_status: string;
  last_error: string;
}

export interface MarkEmailAuthStatusResponse {
  mailbox: EmailMailbox | undefined;
}

export interface UpsertEmailMailboxRequest {
  mailbox: EmailMailbox | undefined;
}

export interface UpsertEmailMailboxResponse {
  mailbox: EmailMailbox | undefined;
}

export interface ListEmailMailboxesRequest {
  status: string;
  limit: number;
}

export interface ListEmailMailboxesResponse {
  mailboxes: EmailMailbox[];
}

export interface DeleteMailboxRequest {
  email_address: string;
}

export interface DeleteMailboxResponse {
  deleted: boolean;
}

export interface WaitForEmailRequest {
  email_address: string;
  /** e.g., "OTP" or "验证码" */
  subject_keyword: string;
  timeout_seconds: number;
  issued_after_unix: number;
}

export interface WaitForEmailResponse {
  found: boolean;
  /** the OTP */
  content_extracted: string;
}

export interface EmailInboxMessage {
  id: string;
  mailbox_email: string;
  subject: string;
  from_address: string;
  body_preview: string;
  received_at_unix: number;
  recipients: string[];
  otp: string;
}

export interface FetchInboxesRequest {
  limit_per_mailbox: number;
  max_mailboxes: number;
  email_address: string;
}

export interface FetchMailboxInboxResult {
  mailbox: EmailMailbox | undefined;
  messages: EmailInboxMessage[];
  error_message: string;
}

export interface FetchInboxesResponse {
  results: FetchMailboxInboxResult[];
  mailbox_count: number;
  fetched_count: number;
  failed_count: number;
  message_count: number;
}
