// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_account.proto

/* eslint-disable */
import type { Account } from "./account_db";

export const protobufPackage = "orchestrator";

export interface AccountSpec {
  account_id: string;
  email: string;
  password: string;
}

export interface AccountRef {
  account_id: string;
  plus_trial_known: boolean;
  plus_trial_eligible: boolean;
  plus_active: boolean;
  tier: string;
}

export interface EnsureAccountInput {
  account: AccountSpec | undefined;
}

export interface CreateGPTAccountRequest {
  email: string;
  password: string;
  account_id: string;
}

export interface CreateGPTAccountResponse {
  account: Account | undefined;
  error_message: string;
}

export interface PersistRegisteredInput {
  account_id: string;
  session_token: string;
  access_token: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
}

export interface RegisterActivityOutput {
  session_token: string;
  access_token: string;
  device_id: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
  checkout_url: string;
  data: { [key: string]: any } | undefined;
}

export interface BrowserAuthStartInput {
  job_id: string;
  account_id: string;
  mode: string;
}

export interface BrowserAuthStartOutput {
  account_id: string;
  flow_id: string;
  email: string;
  otp_required: boolean;
  otp_issued_after_unix: number;
  otp_timeout_seconds: number;
  result: RegisterActivityOutput | undefined;
  data: { [key: string]: any } | undefined;
}

export interface BrowserAuthCompleteInput {
  job_id: string;
  account_id: string;
  flow_id: string;
  mode: string;
  otp_param: string;
  submitted_at_param: string;
  otp_issued_after_unix: number;
  otp_source: string;
}

export interface BrowserAuthCancelInput {
  flow_id: string;
  mode: string;
}

export interface LoginSessionActivityOutput {
  session_token: string;
  access_token: string;
  device_id: string;
  data: { [key: string]: any } | undefined;
}

export interface RegisterAccountRequest {
  email: string;
  password: string;
  account_id: string;
}

export interface RegisterAccountResponse {
  job_id: string;
  session_token: string;
  plus_trial_eligible: boolean;
  error_message: string;
  checkout_url: string;
  access_token: string;
}

export interface LoginAccountRequest {
  account_id: string;
}

export interface LoginAccountResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface RegisterAndActivateAccountRequest {
  email: string;
  password: string;
  account_id: string;
}

export interface RegisterAndActivateAccountResponse {
  job_id: string;
  session_token: string;
  plus_trial_eligible: boolean;
  checkout_url: string;
  activation_success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
  access_token: string;
}

export interface RegisterAccountWorkflowInput {
  job_id: string;
  account: AccountSpec | undefined;
}

export interface RegisterAccountWorkflowResult {
  job_id: string;
  session_token: string;
  access_token: string;
  plus_trial_eligible: boolean;
  checkout_url: string;
  error_message: string;
}

export interface LoginSessionWorkflowInput {
  job_id: string;
  account_id: string;
}

export interface LoginSessionWorkflowResult {
  job_id: string;
  session_token: string;
  access_token: string;
  error_message: string;
}

export interface RegisterAndActivateWorkflowInput {
  job_id: string;
  account: AccountSpec | undefined;
}

export interface RegisterAndActivateWorkflowResult {
  job_id: string;
  session_token: string;
  access_token: string;
  plus_trial_eligible: boolean;
  checkout_url: string;
  activation_success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
}
